name: slack Notification on PR
on:
  pull_request:
    branches:
      - main
jobs:
  generate_slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Run Python Script
        env:
          SLACK_BOT_TOKEN : ${{ secrets.SLACK_BOT_TOKEN }}
        run: python .github/workflows/python/api.py
        