name: slack Notification on PR
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python Script
        env:
          SLACK_BOT_TOKEN : ${{secret.SLACK_BOT_TOKEN }}
        uses: python .github/workflows/python/api.py
